### ISSUE TITLE
eda function not compatible with NER task

### ISSUE THREAD

**Issue by gunturbudi** [WengLab-InformaticsResearch/UMLS-EDA#1]
Hello, I found that the `eda.py` is not compatible with NER task, since the parameter of the `eda` function from `augment4ner.py` is not match with the definition in `src/eda.py`

**Comment by Tian312** [comment]
@gunturbudi Thank you for your interests. Could you be more specific on that "the parameter of the eda function from augment4ner.py is not match with eda.py"?

**Comment by gunturbudi** [comment]
Hello, sorry for not providing a more detailed explanation in my first post.

In `augment4ner.py` line 70, the first two parameter mention `sentence` and `label`

`aug_sentences = eda(sentence,label,alpha_sr=alpha, alpha_ri=alpha, alpha_rs=alpha, p_rd=alpha, num_aug=num_aug)`

However, here is the definition of the function in the `src/eda.py`

```
def eda(sentence, alpha_sr=0.2, alpha_ri=0.2, alpha_rs=0.2, p_rd=0.2,alpha_umls=0.5,num_aug=9,task = "sent"):
    #task = "sent" sentence classification
    #task= "re" relation extraction "index sentence label"
```

Which not compatible with the augment4ner.py, and produce an error when I try to run it.

**Comment by Tian312** [comment]
@gunturbudi I've updated `src/eda4ner.py`. Can you try run `python augment4ner.py --input example/example4ner.conll --output example/example4ner.conll.augmented` if you have QuickUMLS installed?

**Comment by gunturbudi** [comment]
@Tian312 It is working now. Thank you very much :)

I found another issue on codecs library, but I guess I'll post it on another issues.

Thanks again!
